# Generated by Django 3.2.6 on 2021-08-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='url_name',
            field=models.CharField(default='', max_length=99, unique=True),
            preserve_default=False,
        ),
    ]
