# Generated by Django 3.2.6 on 2021-08-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=90)),
                ('cover_url', models.CharField(max_length=255)),
                ('url_name', models.CharField(max_length=99, unique=True)),
            ],
        ),
    ]
