# Generated by Django 3.2.6 on 2021-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_projectposttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='tags',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
